# Generated by Django 3.0.7 on 2020-07-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='company',
            new_name='user',
        ),
    ]
