# Generated by Django 2.2.5 on 2020-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20200710_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(
                blank=True, null=True, upload_to='company_images'),
        ),
    ]
