# Generated by Django 2.2.5 on 2020-07-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0006_auto_20200711_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('status', models.CharField(
                    choices=[
                        ('1', 'Ищу работу'),
                        ('2', 'Рассматриваю предложения'),
                        ('3', 'Не ищу работу')], max_length=30)),
                ('salary', models.IntegerField()),
                ('specialty', models.CharField(
                    choices=[
                        ('backend', 'Бэкенд'), ('frontend', 'Фронтенд'),
                        ('gamedev', 'Геймдев'), ('devops', 'Девопс'),
                        ('design', 'Дизайн'), ('products', 'Продукты'),
                        ('management', 'Менеджмент'),
                        ('testing', 'Тестирование')], max_length=30)),
                ('grade', models.CharField(
                    choices=[
                        ('trainee', 'Стажер'), ('junior', 'Джуниор'),
                        ('middle', 'Миддл'), ('senior', 'Синьор'),
                        ('lead', 'Лид')], max_length=30)),
                ('education', models.TextField()),
                ('experience', models.CharField(max_length=15)),
                ('portfolio', models.TextField()),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
